from .list_translates_is_empty import empty_translates_keyboard
from .learning_translate_from_past import past_translates_keyboard
from .shortage_todays_translates import shortage_translates_keyboard
